import type { LegalBlock } from './legal'

// Verbatim content — extracted from the source .docx. Do not paraphrase.
export const ACCESSIBILITY_TITLE = "ACCESSIBILITY STATEMENT"
export const ACCESSIBILITY_UPDATED = "Effective Date: July 1, 2026"

export const ACCESSIBILITY: LegalBlock[] = [
  { type: "para", text: "Strategic Advisers LLC is committed to providing an accessible and inclusive experience for all individuals, including people with disabilities." },
  { type: "para", text: "We believe everyone should be able to access information, products, services, programs, and resources offered through our website and digital properties. We continually work to improve the accessibility and usability of our digital experiences and to provide reasonable access to all users." },
  { type: "heading", text: "Our Accessibility Commitment" },
  { type: "para", text: "We strive to design, develop, maintain, and improve our website with accessibility in mind." },
  { type: "para", text: "As part of these efforts, we use generally recognized accessibility standards and best practices as guidance, including the Web Content Accessibility Guidelines (“WCAG”) published by the World Wide Web Consortium (“W3C”)." },
  { type: "para", text: "Our general accessibility goal is to work toward substantial conformance with WCAG 2.2 Level AA, where appropriate. Where another accessibility standard or legal requirement applies, we seek to address the applicable requirements." },
  { type: "para", text: "Accessibility is an ongoing effort. Technologies, standards, content, and user needs continue to evolve, and we regularly evaluate opportunities to improve the accessibility of our digital experiences." },
  { type: "heading", text: "Accessibility Features and Practices" },
  { type: "para", text: "Depending on the content and functionality of the website, our accessibility efforts may include practices designed to support:" },
  { type: 'list', items: [
    "Keyboard navigation;",
    "Screen readers and other assistive technologies;",
    "Alternative text for meaningful images;",
    "Appropriate headings and page structure;",
    "Descriptive links and buttons;",
    "Sufficient color contrast;",
    "Text resizing and browser zoom;",
    "Form labels and instructions;",
    "Visible keyboard focus indicators;",
    "Captions, transcripts, or other alternatives for multimedia where appropriate;",
    "Consistent navigation and page organization; and",
    "Responsive functionality across different devices and screen sizes.",
  ] },
  { type: "para", text: "We may use a combination of automated accessibility testing, manual review, user feedback, accessibility tools, and ongoing website maintenance to identify and address potential accessibility barriers." },
  { type: "heading", text: "Assistive Technology" },
  { type: "para", text: "Our website is designed to work with commonly used browsers, operating systems, and assistive technologies." },
  { type: "para", text: "Because assistive technologies, browsers, devices, and individual user settings vary, the experience may differ depending on the technology being used." },
  { type: "para", text: "For the best experience, users are encouraged to use current versions of their web browser, operating system, and assistive technology whenever possible." },
  { type: "heading", text: "Third-Party Content and Services" },
  { type: "para", text: "Our website may contain links to, integrations with, or content provided by third-party websites, platforms, applications, documents, maps, videos, payment systems, scheduling tools, social media services, or other external technologies that we do not own or control." },
  { type: "para", text: "While we encourage third parties to provide accessible and user-friendly experiences, we cannot control or guarantee the accessibility of third-party content or services." },
  { type: "para", text: "If you encounter an accessibility issue involving third-party content accessed through our website, please contact us and we will make reasonable efforts to assist you or provide an alternative method of accessing the applicable information or service when possible." },
  { type: "heading", text: "Documents and Downloadable Content" },
  { type: "para", text: "Our website may contain documents, PDFs, presentations, forms, or other downloadable materials." },
  { type: "para", text: "We strive to make digital documents accessible where reasonably possible. However, some older, archived, externally provided, or highly specialized documents may not be fully accessible." },
  { type: "para", text: "If you experience difficulty accessing a document, please contact us. We will make reasonable efforts to provide the information in an alternative accessible format when possible." },
  { type: "heading", text: "Video, Audio, and Multimedia" },
  { type: "para", text: "Where multimedia content is used, we strive to provide accessible alternatives such as captions, transcripts, descriptive text, or other accommodations where appropriate." },
  { type: "para", text: "Certain archived, live, third-party, or externally provided multimedia content may have accessibility limitations." },
  { type: "para", text: "If you need assistance accessing multimedia content, please contact us." },
  { type: "heading", text: "Alternative Access" },
  { type: "para", text: "If a disability prevents you from accessing information, completing a transaction, submitting a form, requesting a service, or otherwise using a feature of our website, please contact us." },
  { type: "para", text: "We will make reasonable efforts to provide the information, communication, product, service, or functionality through an alternative accessible method when possible." },
  { type: "para", text: "Our goal is to provide an alternative that offers substantially equivalent access to the information or service." },
  { type: "heading", text: "Accessibility Feedback and Assistance" },
  { type: "para", text: "We welcome feedback about the accessibility of our website." },
  { type: "para", text: "If you experience an accessibility barrier, have difficulty accessing any part of the website, or need information in an alternative format, please contact us at:" },
  { type: "para", text: "msmith@emailstrategic.com" },
  { type: "para", text: "When contacting us, please provide, if possible:" },
  { type: 'list', items: [
    "The webpage, document, or feature where you experienced difficulty;",
    "A brief description of the accessibility issue;",
    "The type of assistive technology or browser you were using, if relevant; and",
    "Your preferred method of contact.",
  ] },
  { type: "para", text: "Providing this information is optional but may help us better understand and address the issue." },
  { type: "para", text: "We will make reasonable efforts to respond to accessibility requests and work toward an appropriate solution." },
  { type: "heading", text: "Ongoing Improvement" },
  { type: "para", text: "Accessibility is not a one-time project. We view accessibility as an ongoing responsibility and continue to assess our website, digital content, technologies, and practices." },
  { type: "para", text: "As websites and technologies change, accessibility issues may occasionally arise despite our efforts. We encourage users to notify us when they encounter a barrier so that we can investigate and address the issue where reasonably possible." },
  { type: "heading", text: "No Retaliation or Discrimination" },
  { type: "para", text: "Strategic Advisers LLC is committed to providing individuals with disabilities an equal opportunity to access our digital information and services." },
  { type: "para", text: "We will not discriminate against an individual because they request an accessibility accommodation, report an accessibility concern, or use assistive technology to access our website." },
  { type: "heading", text: "Changes to This Accessibility Statement" },
  { type: "para", text: "We may update this Accessibility Statement periodically to reflect changes in our website, technology, accessibility practices, standards, or applicable requirements." },
  { type: "para", text: "When we update this statement, we will revise the Effective Date at the top of this page." },
  { type: "heading", text: "Contact Us" },
  { type: "para", text: "For accessibility assistance, accommodations, alternative formats, or questions regarding the accessibility of our website, please contact:" },
  { type: "para", text: "Strategic Advisers LLC\nEmail: msmith@emailstrategic.com" },
]
