import type { LegalBlock } from './legal'

// Verbatim content — extracted from the source .docx. Do not paraphrase.
export const COOKIE_POLICY_TITLE = "COOKIE POLICY"
export const COOKIE_POLICY_UPDATED = "Last Updated: July 1, 2026"

export const COOKIE_POLICY: LegalBlock[] = [
  { type: "para", text: "This Cookie Policy explains how Strategic Advisers LLC (“we,” “us,” or “our”) uses cookies and similar technologies when you visit saprdigital.com (the “Website”)." },
  { type: "para", text: "This Cookie Policy should be read together with our Privacy Policy, which provides additional information about how we collect, use, disclose, and protect personal information." },
  { type: "heading", text: "1. What Are Cookies?" },
  { type: "para", text: "Cookies are small text files or pieces of data that are stored on or accessed from your computer, smartphone, tablet, or other device when you visit a website." },
  { type: "para", text: "Cookies and similar technologies can help websites function properly, remember user preferences, understand how visitors interact with a website, measure advertising performance, and deliver more relevant content and advertising." },
  { type: "para", text: "Depending on the technology involved, we may use cookies as well as similar technologies such as pixels, tags, web beacons, scripts, software development kits, local storage, and device identifiers. For purposes of this Cookie Policy, we generally refer to these technologies collectively as “cookies.”" },
  { type: "para", text: "Cookies may be:" },
  { type: 'def', term: "First-party cookies:", text: "Cookies placed directly by us or on our behalf." },
  { type: 'def', term: "Third-party cookies:", text: "Cookies placed by third-party companies whose technologies or services are incorporated into our Website." },
  { type: 'def', term: "Session cookies:", text: "Cookies that generally expire when you close your browser." },
  { type: 'def', term: "Persistent cookies:", text: "Cookies that remain on your device for a specified period of time or until you delete them." },
  { type: "heading", text: "2. How We Use Cookies" },
  { type: "para", text: "We may use cookies for the following purposes:" },
  { type: "subheading", text: "Strictly Necessary Cookies" },
  { type: "para", text: "These cookies are necessary for the Website to operate and provide features or services you request. They may support functions such as website security, fraud prevention, network management, accessibility, session management, form functionality, or remembering your privacy preferences." },
  { type: "para", text: "Because these cookies are necessary for the Website to function, they generally cannot be disabled through our cookie preference tools." },
  { type: "subheading", text: "Functional Cookies" },
  { type: "para", text: "Functional cookies allow the Website to provide enhanced functionality and personalization. For example, they may remember preferences you have selected, your location or language preferences, or information you previously provided." },
  { type: "para", text: "If you do not allow these cookies, certain Website features may not function as intended." },
  { type: "subheading", text: "Analytics and Performance Cookies" },
  { type: "para", text: "We may use analytics and performance cookies to understand how visitors use our Website." },
  { type: "para", text: "These technologies may collect information such as:" },
  { type: 'list', items: [
    "Pages visited;",
    "Time spent on particular pages;",
    "Links or buttons clicked;",
    "Referring websites;",
    "Browser and device information;",
    "General geographic information;",
    "Website errors;",
    "Traffic patterns; and",
    "Other information regarding interactions with our Website.",
  ] },
  { type: "para", text: "We use this information to measure Website performance, understand how users interact with our content, improve user experience, and make informed decisions about our Website and marketing activities." },
  { type: "subheading", text: "Advertising, Targeting, and Remarketing Cookies" },
  { type: "para", text: "We and our advertising partners may use cookies and similar technologies to measure advertising effectiveness, understand interactions with our advertisements, create audiences, and provide advertising that may be more relevant to your interests." },
  { type: "para", text: "These technologies may help us:" },
  { type: 'list', items: [
    "Determine whether an advertisement resulted in a Website visit or other action;",
    "Measure advertising campaign performance;",
    "Limit how frequently advertisements are displayed;",
    "Create advertising audiences;",
    "Conduct remarketing or retargeting campaigns;",
    "Understand interactions across websites, applications, or devices; and",
    "Deliver or measure interest-based or targeted advertising.",
  ] },
  { type: "para", text: "Depending on applicable law, some of these activities may be considered “targeted advertising,” “cross-context behavioral advertising,” “sharing,” or a “sale” of personal information." },
  { type: "para", text: "Where required by applicable law, we provide mechanisms for users to consent to or opt out of these activities." },
  { type: "subheading", text: "Social Media and Embedded Content" },
  { type: "para", text: "Our Website may contain features, videos, maps, social media tools, or other content provided by third parties." },
  { type: "para", text: "These third parties may use cookies or similar technologies when you interact with their content. Information collected by these third parties is governed by their own privacy policies and practices." },
  { type: "heading", text: "3. Third-Party Technologies" },
  { type: "para", text: "Depending on the services and features used on our Website, we may utilize technologies provided by third parties, such as:" },
  { type: 'list', items: [
    "Website analytics providers;",
    "Search engine advertising platforms;",
    "Social media advertising platforms;",
    "Programmatic advertising platforms;",
    "Customer relationship management platforms;",
    "Marketing automation platforms;",
    "Call tracking providers;",
    "Video hosting providers;",
    "Mapping services;",
    "Website hosting and content delivery providers;",
    "Security and fraud prevention providers; and",
    "Other technology and advertising partners.",
  ] },
  { type: "para", text: "These third parties may collect information directly from your browser or device through cookies and similar technologies. Their collection and use of information are subject to their respective privacy policies." },
  { type: "heading", text: "4. Cookie Preferences and Choices" },
  { type: "para", text: "Depending on your location and applicable law, you may have choices regarding the use of certain cookies." },
  { type: "subheading", text: "Cookie Preference Center" },
  { type: "para", text: "Where available, you can manage your cookie preferences by selecting “Cookie Preferences,” “Privacy Choices,” or a similar link available on our Website." },
  { type: "para", text: "You may be able to accept or reject certain categories of cookies. Strictly necessary cookies may remain active because they are required for the Website to operate." },
  { type: "para", text: "If you change or delete cookies, use another browser or device, or clear your browser storage, you may need to update your preferences again." },
  { type: "subheading", text: "Browser Controls" },
  { type: "para", text: "Most web browsers allow you to manage cookies through browser settings. Depending on your browser, you may be able to block cookies, receive notifications before cookies are stored, or delete cookies that have already been placed on your device." },
  { type: "para", text: "Blocking certain cookies may affect the functionality or performance of the Website." },
  { type: "subheading", text: "Global Privacy Control and Other Opt-Out Preference Signals" },
  { type: "para", text: "Certain browsers, browser extensions, and devices allow users to transmit privacy preference signals, such as the Global Privacy Control (“GPC”)." },
  { type: "para", text: "Where we are legally required to recognize an applicable opt-out preference signal, we will process the signal in accordance with applicable law." },
  { type: "para", text: "Depending on applicable law and our data practices, an applicable signal may be treated as a request to opt out of the sale or sharing of personal information or the use of personal information for targeted advertising." },
  { type: "heading", text: "5. Advertising Choices" },
  { type: "para", text: "Some third-party advertising providers participate in industry programs that allow users to make choices regarding interest-based advertising." },
  { type: "para", text: "You may also be able to limit advertising tracking through your browser, mobile device, advertising platform account settings, or the cookie preference tools available on our Website." },
  { type: "para", text: "Opting out of interest-based or targeted advertising does not necessarily mean that you will stop receiving advertisements. Instead, advertisements you receive may be less tailored to your interests." },
  { type: "heading", text: "6. How Long Cookies Remain on Your Device" },
  { type: "para", text: "The length of time a cookie remains on your device varies depending on the type and purpose of the cookie." },
  { type: "para", text: "Some cookies expire when you close your browser, while others may remain for a specified period of time unless you delete them earlier." },
  { type: "para", text: "Where appropriate, more information regarding individual cookies and their duration may be available through our cookie preference management tool." },
  { type: "heading", text: "7. Personal Information Collected Through Cookies" },
  { type: "para", text: "Depending on the technology used, cookies and similar technologies may collect or generate information such as:" },
  { type: 'list', items: [
    "Internet Protocol (IP) address;",
    "Browser type;",
    "Device type;",
    "Operating system;",
    "Device identifiers;",
    "Pages viewed;",
    "Links clicked;",
    "Referring and exit pages;",
    "Approximate geographic location;",
    "Date and time of visits;",
    "Advertising identifiers;",
    "Website interactions;",
    "Conversion information; and",
    "Other online activity information.",
  ] },
  { type: "para", text: "Some of this information may constitute personal information or personal data under applicable privacy laws." },
  { type: "para", text: "For more information regarding the personal information we collect, how we use it, the circumstances in which we disclose it, and the privacy rights that may be available to you, please review our Privacy Policy." },
  { type: "heading", text: "8. Your Privacy Rights" },
  { type: "para", text: "Depending on where you live and applicable law, you may have certain rights regarding your personal information, including rights to access, correct, delete, or obtain a copy of certain personal information." },
  { type: "para", text: "Please review our Privacy Policy for additional information regarding available privacy rights and instructions for submitting a privacy request." },
  { type: "heading", text: "9. International Visitors" },
  { type: "para", text: "Privacy and cookie requirements vary by jurisdiction." },
  { type: "para", text: "Where required by applicable law, we may request your consent before using non-essential cookies or similar technologies." },
  { type: "para", text: "You may withdraw or modify your consent through the cookie preference tools available on the Website, where applicable. Withdrawal of consent does not affect processing that occurred before consent was withdrawn." },
  { type: "heading", text: "10. Changes to This Cookie Policy" },
  { type: "para", text: "We may update this Cookie Policy periodically to reflect changes in our use of cookies, technologies, services, business practices, or applicable laws." },
  { type: "para", text: "When we update this Cookie Policy, we will revise the “Last Updated” date at the top of this page." },
  { type: "para", text: "We encourage you to review this Cookie Policy periodically for information about our use of cookies and similar technologies." },
  { type: "heading", text: "11. Contact Us" },
  { type: "para", text: "Questions regarding this Cookie Policy or our privacy practices may be directed to:" },
  { type: "para", text: "Strategic Advisers LLC\nEmail: msmith@emailstrategic.com" },
  { type: "para", text: "For more information about our privacy practices, please review our Privacy Policy." },
]
