import type { LegalBlock } from './legal'

// Verbatim content — extracted from the source .docx. Do not paraphrase.
export const PRIVACY_POLICY_TITLE = "PRIVACY POLICY"
export const PRIVACY_POLICY_UPDATED = "Effective Date: July 1, 2026"

export const PRIVACY_POLICY: LegalBlock[] = [
  { type: "para", text: "Strategic Advisers LLC (“Company,” “we,” “us,” or “our”) respects your privacy. This Privacy Policy explains how we collect, use, disclose, and protect information when you visit saprdigital.com or otherwise interact with our websites, digital services, communications, advertisements, forms, social media pages, events, products, or services that link to this Privacy Policy collectively, the “Services.”" },
  { type: "para", text: "By accessing or using the Services, you acknowledge the practices described in this Privacy Policy." },
  { type: "heading", text: "1. Scope of This Privacy Policy" },
  { type: "para", text: "This Privacy Policy applies to personal information collected through the Services and through related interactions with us." },
  { type: "para", text: "“Personal information” means information that identifies, relates to, describes, is reasonably capable of being associated with, or could reasonably be linked to an individual or household. The definition may vary depending on applicable law." },
  { type: "para", text: "This Privacy Policy does not apply to information governed by a separate privacy notice provided by us, including any industry-specific, customer-specific, employee, applicant, financial, medical, or other legally required privacy notice." },
  { type: "heading", text: "2. Information We Collect" },
  { type: "para", text: "The information we collect depends on how you interact with us and which Services you use." },
  { type: "subheading", text: "Information You Provide Directly" },
  { type: "para", text: "We may collect information you provide to us, including:" },
  { type: 'list', items: [
    "Name;",
    "Email address;",
    "Telephone number;",
    "Mailing or billing address;",
    "Company, organization, or employer;",
    "Job title;",
    "Account or login information;",
    "Information submitted through contact, registration, request-information, appointment, application, reservation, donation, or inquiry forms;",
    "Communications and correspondence with us;",
    "Customer service requests;",
    "Survey, contest, promotion, or event information;",
    "Transaction, order, billing, or payment-related information;",
    "Reviews, testimonials, comments, or other content you submit;",
    "Employment application information, such as work history, education, qualifications, and résumé information; and",
    "Any other information you choose to provide.",
  ] },
  { type: "para", text: "Payment information may be collected and processed directly by a third-party payment provider. We may not receive or store complete payment card details." },
  { type: "subheading", text: "Information Collected Automatically" },
  { type: "para", text: "When you use the Services, we and our service providers may automatically collect information such as:" },
  { type: 'list', items: [
    "Internet Protocol address;",
    "Browser type and version;",
    "Device type;",
    "Operating system;",
    "Device identifiers;",
    "Referring and exit pages;",
    "Pages viewed;",
    "Links, buttons, or advertisements clicked;",
    "Dates and times of visits;",
    "Time spent using the Services;",
    "General or approximate geographic location;",
    "Search activity;",
    "Form interactions;",
    "Advertising identifiers;",
    "Conversion and attribution information;",
    "Website errors and performance information; and",
    "Other information regarding your interaction with the Services.",
  ] },
  { type: "para", text: "We may collect this information through cookies, pixels, tags, web beacons, scripts, local storage, software development kits, device identifiers, and similar technologies." },
  { type: "para", text: "Please review our Cookie Policy for additional information about these technologies and the choices that may be available to you." },
  { type: "subheading", text: "Information From Other Sources" },
  { type: "para", text: "We may receive information from other sources, including:" },
  { type: 'list', items: [
    "Advertising and analytics providers;",
    "Social media platforms;",
    "Marketing and technology partners;",
    "Customer relationship management platforms;",
    "Publicly available sources;",
    "Business partners;",
    "Referral sources;",
    "Event organizers;",
    "Data providers;",
    "Affiliates;",
    "Service providers; and",
    "Other individuals or organizations.",
  ] },
  { type: "para", text: "If you interact with us through a social media platform or another third-party service, that platform may provide us with information in accordance with its own policies and your account settings." },
  { type: "heading", text: "3. Categories of Personal Information" },
  { type: "para", text: "Depending on how you interact with us, we may collect the following categories of personal information:" },
  { type: "subheading", text: "Identifiers" },
  { type: "para", text: "Examples include your name, email address, postal address, telephone number, account name, online identifier, Internet Protocol address, or similar identifiers." },
  { type: "subheading", text: "Customer and Contact Information" },
  { type: "para", text: "Examples include contact details, account information, signature, communication preferences, and other information you provide when requesting or receiving products, information, or services." },
  { type: "subheading", text: "Commercial Information" },
  { type: "para", text: "Examples include records of products or services considered, requested, purchased, scheduled, donated to, applied for, or otherwise obtained, as well as transaction and engagement history." },
  { type: "subheading", text: "Internet or Other Electronic Network Activity" },
  { type: "para", text: "Examples include browsing history, search history, pages viewed, advertisements viewed, links clicked, device information, and interactions with websites, applications, advertisements, emails, or other digital content." },
  { type: "subheading", text: "Geolocation Information" },
  { type: "para", text: "We may collect general or approximate location information based on your Internet Protocol address, device information, or interaction with the Services." },
  { type: "subheading", text: "Audio, Electronic, Visual, or Similar Information" },
  { type: "para", text: "Examples may include photographs, videos, voicemail messages, recordings, or other content submitted to us or captured during interactions where permitted by law." },
  { type: "subheading", text: "Professional, Employment, or Education Information" },
  { type: "para", text: "Examples include employer, job title, professional qualifications, employment history, résumé information, education history, or information submitted in connection with employment or educational opportunities." },
  { type: "subheading", text: "Inferences" },
  { type: "para", text: "We may draw inferences from information we collect to understand interests, preferences, likely behavior, advertising effectiveness, or interactions with our Services." },
  { type: "subheading", text: "Sensitive Personal Information" },
  { type: "para", text: "In limited circumstances, you may choose to provide information that is considered sensitive under applicable law." },
  { type: "para", text: "We do not use or disclose sensitive personal information for the purpose of inferring characteristics about an individual except where permitted by applicable law. Please do not provide sensitive information through general website forms unless it is specifically requested and necessary for the applicable service." },
  { type: "heading", text: "4. How We Use Personal Information" },
  { type: "para", text: "We may use personal information to:" },
  { type: 'list', items: [
    "Provide, operate, maintain, and improve the Services;",
    "Respond to inquiries and requests;",
    "Provide requested information, products, or services;",
    "Process registrations, applications, appointments, reservations, transactions, donations, or orders;",
    "Communicate with customers, prospective customers, applicants, donors, students, patients, residents, members, business partners, or other individuals;",
    "Provide customer service and support;",
    "Personalize content and user experiences;",
    "Maintain accounts and preferences;",
    "Send administrative information;",
    "Send marketing, promotional, educational, fundraising, or informational communications;",
    "Measure and improve advertising and marketing campaigns;",
    "Conduct analytics and research;",
    "Understand how people use and interact with the Services;",
    "Develop and improve products, services, websites, communications, and marketing;",
    "Authenticate users and protect accounts;",
    "Detect, investigate, and prevent fraud, misuse, security incidents, or illegal activity;",
    "Protect our rights, property, security, employees, customers, users, and others;",
    "Comply with legal, regulatory, contractual, and reporting obligations;",
    "Enforce agreements, policies, and terms;",
    "Evaluate or complete a merger, acquisition, financing, restructuring, sale, transfer, or similar business transaction;",
    "Process employment applications and manage recruiting activities; and",
    "Fulfill any other purpose disclosed when information is collected or with your direction or consent.",
  ] },
  { type: "para", text: "We may combine information collected from different sources for the purposes described in this Privacy Policy." },
  { type: "para", text: "We may also aggregate or de-identify information so that it can no longer reasonably be associated with an individual. We may use and disclose aggregated or de-identified information for lawful purposes." },
  { type: "heading", text: "5. How We Disclose Personal Information" },
  { type: "para", text: "We may disclose personal information to the following categories of recipients:" },
  { type: "subheading", text: "Service Providers" },
  { type: "para", text: "We may disclose information to companies that perform services on our behalf, such as:" },
  { type: 'list', items: [
    "Website hosting;",
    "Cloud storage;",
    "Information technology;",
    "Cybersecurity;",
    "Analytics;",
    "Advertising;",
    "Email and text message delivery;",
    "Customer relationship management;",
    "Payment processing;",
    "Call tracking;",
    "Form processing;",
    "Scheduling;",
    "Customer support;",
    "Professional consulting;",
    "Data management;",
    "Marketing;",
    "Printing and mailing; and",
    "Other operational services.",
  ] },
  { type: "para", text: "These providers may access personal information as necessary to perform services for us." },
  { type: "subheading", text: "Advertising and Analytics Partners" },
  { type: "para", text: "We may disclose identifiers, device information, Internet or electronic network activity, approximate location, advertising information, and inferences to advertising, analytics, social media, and technology partners." },
  { type: "para", text: "These partners may use information to:" },
  { type: 'list', items: [
    "Measure website traffic;",
    "Analyze user activity;",
    "Attribute conversions;",
    "Create advertising audiences;",
    "Measure advertising effectiveness;",
    "Limit advertising frequency;",
    "Personalize content; and",
    "Provide or measure targeted, personalized, or interest-based advertising.",
  ] },
  { type: "para", text: "Some privacy laws may define certain digital advertising disclosures as a “sale,” “sharing,” or use for “targeted advertising,” even when no money is exchanged." },
  { type: "para", text: "We do not sell personal information in exchange for money. Where required by applicable law, we provide individuals with the ability to opt out of activities legally defined as selling, sharing, or targeted advertising." },
  { type: "subheading", text: "Affiliates and Related Organizations" },
  { type: "para", text: "We may disclose information to affiliated companies, parent organizations, subsidiaries, related entities, franchisees, locations, departments, or organizations under common ownership or control." },
  { type: "subheading", text: "Business Partners" },
  { type: "para", text: "We may disclose information to business partners in connection with jointly offered programs, events, promotions, services, referrals, or other business activities." },
  { type: "subheading", text: "Legal, Safety, and Compliance Recipients" },
  { type: "para", text: "We may disclose information when we believe disclosure is necessary or appropriate to:" },
  { type: 'list', items: [
    "Comply with applicable laws, regulations, legal processes, court orders, or government requests;",
    "Cooperate with law enforcement or regulatory authorities;",
    "Protect legal rights or defend legal claims;",
    "Enforce agreements and policies;",
    "Detect or prevent fraud, misuse, security incidents, or illegal activity; or",
    "Protect the safety, rights, property, or security of the Company, our users, or others.",
  ] },
  { type: "subheading", text: "Business Transactions" },
  { type: "para", text: "We may disclose or transfer information in connection with a proposed or completed merger, acquisition, financing, reorganization, bankruptcy, sale of assets, transfer of operations, or similar business transaction." },
  { type: "subheading", text: "At Your Direction or With Your Consent" },
  { type: "para", text: "We may disclose information when you direct us to do so, consent to the disclosure, or intentionally use the Services to interact with a third party." },
  { type: "heading", text: "6. Cookies and Similar Technologies" },
  { type: "para", text: "We and third parties may use cookies and similar technologies to operate the Services, remember preferences, analyze activity, measure performance, prevent fraud, personalize content, and conduct or measure advertising." },
  { type: "para", text: "The technologies used through our Services may include:" },
  { type: 'list', items: [
    "Essential cookies;",
    "Functional cookies;",
    "Analytics cookies;",
    "Advertising cookies;",
    "Conversion tracking technologies;",
    "Social media pixels;",
    "Remarketing and retargeting technologies;",
    "Embedded content; and",
    "Similar tracking technologies.",
  ] },
  { type: "para", text: "You can learn more about these practices and available choices by reviewing our Cookie Policy and using any cookie preference tool available on the Website." },
  { type: "para", text: "Browser controls that delete or block cookies may affect the availability or functionality of certain features." },
  { type: "heading", text: "7. Targeted Advertising and Privacy Preference Signals" },
  { type: "para", text: "We and our advertising partners may use personal information collected across websites, applications, or services to provide or measure advertising that may be more relevant to your interests." },
  { type: "para", text: "Depending on where you live, you may have the right to opt out of:" },
  { type: 'list', items: [
    "The sale of personal information;",
    "The sharing of personal information;",
    "Targeted advertising;",
    "Cross-context behavioral advertising; or",
    "Certain profiling activities.",
  ] },
  { type: "para", text: "You may exercise applicable rights through any “Your Privacy Choices,” “Do Not Sell or Share My Personal Information,” or cookie preference link made available through the Services. You may also contact us at msmith@emailstrategic.com." },
  { type: "para", text: "Certain browsers and browser extensions allow users to transmit opt-out preference signals, such as Global Privacy Control. Where required by applicable law, we process recognized preference signals as requests to opt out of applicable selling, sharing, or targeted advertising for the browser or device transmitting the signal." },
  { type: "para", text: "Because these signals may be browser- and device-specific, you may need to apply the preference separately on each browser and device you use." },
  { type: "heading", text: "8. Email and Text Message Communications" },
  { type: "para", text: "You may unsubscribe from promotional emails by selecting the unsubscribe link included in the email." },
  { type: "para", text: "Even if you unsubscribe from promotional messages, we may continue to send non-promotional communications, such as responses to inquiries, transaction information, account notices, security alerts, or other service-related messages." },
  { type: "para", text: "Where text messaging is offered, you may opt out of promotional text messages by following the instructions in the message, such as replying “STOP.” Message and data rates may apply." },
  { type: "heading", text: "9. Retention of Personal Information" },
  { type: "para", text: "We retain personal information for as long as reasonably necessary to fulfill the purposes described in this Privacy Policy, unless a longer retention period is required or permitted by law." },
  { type: "para", text: "The criteria used to determine retention periods may include:" },
  { type: 'list', items: [
    "The length of our relationship with you;",
    "The nature and sensitivity of the information;",
    "The purposes for which the information was collected;",
    "Operational and business requirements;",
    "Legal, contractual, accounting, and reporting obligations;",
    "Applicable limitation periods;",
    "Security and fraud-prevention needs; and",
    "The need to establish, exercise, or defend legal claims.",
  ] },
  { type: "para", text: "When information is no longer reasonably necessary, we may delete, de-identify, or securely dispose of it in accordance with applicable requirements and our retention practices." },
  { type: "heading", text: "10. Information Security" },
  { type: "para", text: "We use reasonable administrative, technical, and physical safeguards designed to protect personal information." },
  { type: "para", text: "However, no website, Internet transmission, electronic storage system, or security measure is completely secure. We cannot guarantee the absolute security of information." },
  { type: "para", text: "You are responsible for using appropriate precautions when submitting information online and for maintaining the confidentiality of any account credentials." },
  { type: "heading", text: "11. Your Privacy Rights" },
  { type: "para", text: "Depending on where you live and applicable law, you may have the right to:" },
  { type: 'list', items: [
    "Confirm whether we process your personal information;",
    "Request access to personal information;",
    "Request correction of inaccurate personal information;",
    "Request deletion of personal information;",
    "Obtain a portable copy of certain personal information;",
    "Opt out of the sale or sharing of personal information;",
    "Opt out of targeted advertising;",
    "Opt out of certain profiling activities;",
    "Limit certain uses or disclosures of sensitive personal information;",
    "Withdraw consent where processing is based on consent;",
    "Object to or restrict certain processing; and",
    "Appeal a decision regarding a privacy request.",
  ] },
  { type: "para", text: "These rights are subject to applicable limitations, exceptions, eligibility requirements, and verification procedures." },
  { type: "subheading", text: "Submitting a Request" },
  { type: "para", text: "To submit a privacy request, contact us at:" },
  { type: "para", text: "Email: msmith@emailstrategic.com" },
  { type: "para", text: "Please describe the nature of your request and provide enough information for us to reasonably identify you and respond." },
  { type: "para", text: "We may need to verify your identity before completing a request. Verification may require us to confirm information associated with you or request additional information. We will use verification information only for identity verification, security, fraud prevention, and legal compliance." },
  { type: "para", text: "We may deny or limit a request where permitted by law, including when we cannot reasonably verify identity, the request is fraudulent or excessive, or the information is subject to a legal exception. When required, we will explain the reason for the denial and provide information about any available appeal process." },
  { type: "subheading", text: "Authorized Agents" },
  { type: "para", text: "Where permitted by law, you may designate an authorized agent to submit a request on your behalf." },
  { type: "para", text: "We may require proof that you authorized the agent and may also require you to verify your identity directly with us." },
  { type: "subheading", text: "Non-Discrimination" },
  { type: "para", text: "We will not unlawfully discriminate against you for exercising an applicable privacy right." },
  { type: "subheading", text: "Appeals" },
  { type: "para", text: "If we deny a privacy request and applicable law provides a right to appeal, you may submit an appeal by emailing msmith@emailstrategic.com and including “Privacy Request Appeal” in the subject line." },
  { type: "heading", text: "12. Additional California Disclosures" },
  { type: "para", text: "This section applies where the California Consumer Privacy Act, as amended, applies to our processing of personal information." },
  { type: "para", text: "During the preceding 12 months, we may have collected the categories of personal information described in Section 3 of this Privacy Policy." },
  { type: "para", text: "We may obtain personal information from:" },
  { type: 'list', items: [
    "You directly;",
    "Your browser or device;",
    "Your interactions with our Services;",
    "Service providers;",
    "Advertising and analytics companies;",
    "Social media platforms;",
    "Business partners;",
    "Affiliates;",
    "Publicly available sources; and",
    "Other individuals or organizations.",
  ] },
  { type: "para", text: "We may collect, use, and disclose these categories of information for the business and commercial purposes described in Sections 4 and 5." },
  { type: "para", text: "During the preceding 12 months, we may have disclosed personal information to service providers, affiliates, business partners, advertising and analytics partners, government or legal recipients, and parties involved in business transactions." },
  { type: "para", text: "We do not sell personal information in exchange for money." },
  { type: "para", text: "Our disclosure of identifiers, Internet or electronic network activity, approximate location information, advertising information, and inferences to advertising or analytics partners may be considered “selling” or “sharing” under California law." },
  { type: "para", text: "California residents may exercise applicable rights as described in Section 11. Applicable opt-out requests may also be submitted through any “Your Privacy Choices” or “Do Not Sell or Share My Personal Information” link available on the Website." },
  { type: "para", text: "We do not knowingly sell or share the personal information of individuals under 16 years of age." },
  { type: "para", text: "We do not use or disclose sensitive personal information for purposes that require a right to limit under applicable California law unless otherwise stated at or before the time of collection." },
  { type: "para", text: "California residents may also request information regarding certain disclosures of personal information to third parties for their own direct marketing purposes, where applicable." },
  { type: "heading", text: "13. Children’s Privacy" },
  { type: "para", text: "The Services are intended for a general audience and are not directed to children under 13." },
  { type: "para", text: "We do not knowingly collect personal information online from children under 13 through general-audience Services. If we learn that we collected personal information from a child under 13 in a manner not permitted by law, we will take reasonable steps to delete it." },
  { type: "para", text: "A parent or legal guardian who believes a child has provided personal information may contact us at msmith@emailstrategic.com." },
  { type: "para", text: "Services specifically directed to children, students, minors, or families may provide an additional privacy notice or obtain consent where required." },
  { type: "heading", text: "14. Third-Party Websites and Services" },
  { type: "para", text: "The Services may contain links to websites, platforms, applications, or services operated by third parties." },
  { type: "para", text: "We do not control and are not responsible for the privacy, security, content, or practices of third parties. This Privacy Policy does not apply to third-party services." },
  { type: "para", text: "We encourage you to review the privacy policies of any third-party services you use." },
  { type: "heading", text: "15. Social Media" },
  { type: "para", text: "We may maintain pages or profiles on social media platforms." },
  { type: "para", text: "Information you provide through a social media platform may be collected and processed by both us and the applicable platform. Your interactions with the platform are governed by its own terms, settings, and privacy policies." },
  { type: "para", text: "Information posted publicly or shared through public social media features may be visible to others." },
  { type: "heading", text: "16. International Visitors" },
  { type: "para", text: "The Services may be operated from or supported in the United States. If you access the Services from another country, your information may be transferred to, processed, or stored in the United States or other countries where we or our service providers operate." },
  { type: "para", text: "Privacy and data protection laws in those countries may differ from the laws in your country." },
  { type: "para", text: "Where required by applicable law, we rely on an appropriate legal basis to process personal information, which may include:" },
  { type: 'list', items: [
    "Performance of a contract;",
    "Compliance with a legal obligation;",
    "Our legitimate interests or the legitimate interests of others;",
    "Protection of vital interests; or",
    "Your consent.",
  ] },
  { type: "para", text: "Individuals in certain jurisdictions may have rights to access, correct, delete, restrict, object to, or obtain a portable copy of personal information and may have the right to withdraw consent." },
  { type: "para", text: "You may contact us at msmith@emailstrategic.com regarding an applicable privacy right. You may also have the right to submit a complaint to the data protection authority where you live or work." },
  { type: "heading", text: "17. Changes to This Privacy Policy" },
  { type: "para", text: "We may update this Privacy Policy periodically to reflect changes in our Services, technologies, practices, legal requirements, or other factors." },
  { type: "para", text: "When we update this Privacy Policy, we will revise the Effective Date at the top of the policy. Material changes may also be communicated through the Website or by other appropriate means." },
  { type: "para", text: "Your continued use of the Services after an updated Privacy Policy becomes effective indicates your acknowledgment of the updated policy." },
  { type: "heading", text: "18. Contact Us" },
  { type: "para", text: "Questions, concerns, or requests regarding this Privacy Policy or our privacy practices may be submitted to:" },
  { type: "para", text: "Strategic Advisers LLC\nEmail: msmith@emailstrategic.com" },
]
